# Generated by Django 2.1.7 on 2020-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=32)),
                ('course', models.CharField(choices=[(1, '甘口'), (2, '普通'), (3, '辛口')], max_length=2)),
                ('page_count', models.IntegerField()),
                ('concept', models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')])),
                ('theme', models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')])),
                ('character', models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')])),
                ('impression', models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')])),
                ('structure', models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')])),
                ('scene', models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')])),
                ('exposition', models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')])),
                ('dialogue', models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')])),
                ('total', models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')])),
                ('concept_comment', models.TextField()),
                ('theme_comment', models.TextField()),
                ('character_comment', models.TextField()),
                ('impression_comment', models.TextField()),
                ('structure_comment', models.TextField()),
                ('scene_comment', models.TextField()),
                ('exposition_comment', models.TextField()),
                ('dialogue_comment', models.TextField()),
                ('total_comment', models.TextField()),
            ],
        ),
    ]
