# Generated by Django 2.1.7 on 2020-04-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksheet', '0002_auto_20200415_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='character',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')], default=5),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='character_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='concept',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')], default=5),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='dialogue',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')], default=5),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='dialogue_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='exposition',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')], default=5),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='exposition_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='impression',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')], default=5),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='impression_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='scene',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')], default=5),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='scene_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='structure',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')], default=5),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='structure_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='theme',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')], default=5),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='theme_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='total',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F'), (8, 'G')], default=5),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='total_comment',
            field=models.TextField(blank=True),
        ),
    ]
