# Generated by Django 2.1.7 on 2020-04-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksheet', '0003_auto_20200415_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='course',
            field=models.CharField(choices=[('甘口', '甘口'), ('普通', '普通'), ('辛口', '辛口')], max_length=2),
        ),
    ]
