# Generated by Django 2.1.7 on 2020-04-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksheet', '0004_auto_20200415_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='character',
            field=models.IntegerField(choices=[(1, 'A+'), (2, 'A'), (3, 'A-'), (4, 'B+'), (5, 'B'), (6, 'B-'), (7, 'C+'), (8, 'C'), (9, 'C-')], default=5, verbose_name='キャラクター'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='character_comment',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='concept',
            field=models.IntegerField(choices=[(1, 'A+'), (2, 'A'), (3, 'A-'), (4, 'B+'), (5, 'B'), (6, 'B-'), (7, 'C+'), (8, 'C'), (9, 'C-')], default=5, verbose_name='コンセプト'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='concept_comment',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='dialogue',
            field=models.IntegerField(choices=[(1, 'A+'), (2, 'A'), (3, 'A-'), (4, 'B+'), (5, 'B'), (6, 'B-'), (7, 'C+'), (8, 'C'), (9, 'C-')], default=5, verbose_name='会話文'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='dialogue_comment',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='exposition',
            field=models.IntegerField(choices=[(1, 'A+'), (2, 'A'), (3, 'A-'), (4, 'B+'), (5, 'B'), (6, 'B-'), (7, 'C+'), (8, 'C'), (9, 'C-')], default=5, verbose_name='地の文'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='exposition_comment',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='impression',
            field=models.IntegerField(choices=[(1, 'A+'), (2, 'A'), (3, 'A-'), (4, 'B+'), (5, 'B'), (6, 'B-'), (7, 'C+'), (8, 'C'), (9, 'C-')], default=5, verbose_name='物語'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='impression_comment',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='scene',
            field=models.IntegerField(choices=[(1, 'A+'), (2, 'A'), (3, 'A-'), (4, 'B+'), (5, 'B'), (6, 'B-'), (7, 'C+'), (8, 'C'), (9, 'C-')], default=5, verbose_name='シーン'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='scene_comment',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='structure',
            field=models.IntegerField(choices=[(1, 'A+'), (2, 'A'), (3, 'A-'), (4, 'B+'), (5, 'B'), (6, 'B-'), (7, 'C+'), (8, 'C'), (9, 'C-')], default=5, verbose_name='構成'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='structure_comment',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='theme',
            field=models.IntegerField(choices=[(1, 'A+'), (2, 'A'), (3, 'A-'), (4, 'B+'), (5, 'B'), (6, 'B-'), (7, 'C+'), (8, 'C'), (9, 'C-')], default=5, verbose_name='テーマ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='theme_comment',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='total',
            field=models.IntegerField(choices=[(1, 'A+'), (2, 'A'), (3, 'A-'), (4, 'B+'), (5, 'B'), (6, 'B-'), (7, 'C+'), (8, 'C'), (9, 'C-')], default=5, verbose_name='総合評価'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='total_comment',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
