# Generated by Django 2.1.7 on 2020-04-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksheet', '0005_auto_20200416_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='character_comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='concept_comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='dialogue_comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='exposition_comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='impression_comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='scene_comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='structure_comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='theme_comment',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
