# Generated by Django 2.1.7 on 2020-04-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksheet', '0006_auto_20200416_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='impression',
            field=models.IntegerField(choices=[(1, 'A+'), (2, 'A'), (3, 'A-'), (4, 'B+'), (5, 'B'), (6, 'B-'), (7, 'C+'), (8, 'C'), (9, 'C-')], default=5, verbose_name='ストーリー'),
        ),
    ]
