# Generated by Django 2.1.7 on 2020-04-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksheet', '0007_auto_20200416_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='impression',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='impression_comment',
            new_name='story_comment',
        ),
    ]
