# Generated by Django 2.1.7 on 2020-04-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksheet', '0009_auto_20200416_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='bad_point',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='sheet',
            name='good_point',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
