# Generated by Django 2.1.7 on 2020-04-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksheet', '0010_auto_20200416_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='character',
            field=models.IntegerField(choices=[(9, 'A+'), (8, 'A'), (7, 'A-'), (6, 'B+'), (5, 'B'), (4, 'B-'), (3, 'C+'), (2, 'C'), (1, 'C-')], default=5, verbose_name='キャラクター'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='concept',
            field=models.IntegerField(choices=[(9, 'A+'), (8, 'A'), (7, 'A-'), (6, 'B+'), (5, 'B'), (4, 'B-'), (3, 'C+'), (2, 'C'), (1, 'C-')], default=5, verbose_name='コンセプト'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='dialogue',
            field=models.IntegerField(choices=[(9, 'A+'), (8, 'A'), (7, 'A-'), (6, 'B+'), (5, 'B'), (4, 'B-'), (3, 'C+'), (2, 'C'), (1, 'C-')], default=5, verbose_name='台詞'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='exposition',
            field=models.IntegerField(choices=[(9, 'A+'), (8, 'A'), (7, 'A-'), (6, 'B+'), (5, 'B'), (4, 'B-'), (3, 'C+'), (2, 'C'), (1, 'C-')], default=5, verbose_name='地の文'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='scene',
            field=models.IntegerField(choices=[(9, 'A+'), (8, 'A'), (7, 'A-'), (6, 'B+'), (5, 'B'), (4, 'B-'), (3, 'C+'), (2, 'C'), (1, 'C-')], default=5, verbose_name='シーン'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='story',
            field=models.IntegerField(choices=[(9, 'A+'), (8, 'A'), (7, 'A-'), (6, 'B+'), (5, 'B'), (4, 'B-'), (3, 'C+'), (2, 'C'), (1, 'C-')], default=5, verbose_name='ストーリー'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='structure',
            field=models.IntegerField(choices=[(9, 'A+'), (8, 'A'), (7, 'A-'), (6, 'B+'), (5, 'B'), (4, 'B-'), (3, 'C+'), (2, 'C'), (1, 'C-')], default=5, verbose_name='構成'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='theme',
            field=models.IntegerField(choices=[(9, 'A+'), (8, 'A'), (7, 'A-'), (6, 'B+'), (5, 'B'), (4, 'B-'), (3, 'C+'), (2, 'C'), (1, 'C-')], default=5, verbose_name='テーマ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='total',
            field=models.IntegerField(choices=[(9, 'A+'), (8, 'A'), (7, 'A-'), (6, 'B+'), (5, 'B'), (4, 'B-'), (3, 'C+'), (2, 'C'), (1, 'C-')], default=5, verbose_name='総合評価'),
        ),
    ]
