# Generated by Django 2.1.7 on 2019-03-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190323_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_order',
            new_name='order',
        ),
    ]
